### PR TITLE
Homework3: Ekaterina Tsiunel

### PR DESCRIPTION
**Pull request by ETsiunel**
change readme file + review fixes

### CODE REVIEW

**Comment by ETsiunel** [comment]
new PR created

**Comment by Stml89** [comment]
Please, fix linter issue

**Comment by ETsiunel** [comment]
all fixed

**Comment by Stml89** [comment]
Congrats! Approved!

**Review by Stml89 — APPROVED** [review]

**Comment by Stml89** [comment]
Now you can merge this PR

**Comment by ETsiunel** [comment]
Thank you! Could I merge this PR?

**Pull request merged**
